spring:
  application:
    name: org
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
